### ISSUE TITLE
Why do not implement record block in handler_eth.go

### ISSUE THREAD

**Issue by wangtsiao** [WeizhaoT/geth_peri#1]
Excellent work! thanks to all authors who decided to open source this invaluable code.

I found you implement record transaction arriving time in handler_eth.go to find peers which send victims' transactions. But why did you not implement record block arriving time to find peers which have less distance to miners.

I am not asking this question to ask you authors to implement this part of the code. I am just curios about it. Are there some difficulties? For example, in theory, this method cannot make our nodes near miners.

Looking forward to your answer.

**Comment by wangtsiao** [comment]
> Excellent work! thanks to all authors who decided to open source this invaluable code.
> 
> I found you implement record transaction arriving time in handler_eth.go to find peers which send victims' transactions. But why did you not implement record block arriving time to find peers which have less distance to miners.
> 
> I am not asking this question to ask you authors to implement this part of the code. I am just curios about it. Are there some difficulties? For example, in theory, this method cannot make our nodes near miners.
> 
> Looking forward to your answer.

also, if possible, can I then implement recoding block arriving timestamp ? I want to try it.

**Comment by WeizhaoT** [comment]
Thanks for your interest in our work! 

We didn't record block propagations because we were more interested in frontrunning transactions at that stage of our research. Additionally, if we include block delays into the score function of Peri, there is no justifiable weight to balance block delay and transaction delay. In our experiments, we were trying to reduce direct latencies to transaction sources, so we didn't have to get closer to miners. 

Please feel free to modify the codebase and try it on your own.
